version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: djuser
      POSTGRES_PASSWORD: djpassword
      POSTGRES_DB: djrequests
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgresql+asyncpg://djuser:djpassword@db:5432/djrequests
    depends_on:
      - db

volumes:
  postgres_data: 